name: flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 

    - name: Run tests with flake8
      run: |
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        echo "Log Timestamp: $(date)" > flake8_report.txt
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics >> flake8_report.txt
        echo "Log Timestamp: $(date)" >> flake8_report.txt
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics >> flake8_report.txt

    - name: Upload Flake8 Report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8_report.txt